session_name: "default"
waifu2x_type: "vulkan"

basic:
  input_file: "test1080p.mkv"
  output_file: "asidjasio"

processing:
  block_size: "auto"
  bleed: 2

specific:
  colors_output: true # doesn't work yet