# ===============================================================================
# 
# Purpose: General settings for a Dandere2x session
#
# ===============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# ===============================================================================



session_name: auto
waifu2x_type: vulkan
mindisk: false

basic:
  input_file: samples/yn_moving.mkv
  output_file: samples/yn_moving_2x.mkv

waifu2x:
  denoise_level: 3
  tile_size: 200

video:
  apply_pre_noise: true
  get_video_info_method: ffmpeg # ffmpeg or mediainfo
  frame_extractor_method: cv2 # only option available right now

ffmpeg:
  get_frame_count_method: null_copy # only option available right now
  get_frame_rate_method: ffprobe # only option available right now
  get_resolution_method: ffprobe # only option available right now

processing:
  extracted_images_extension: .jpg
  block_size: auto
  bleed: 2

vapoursynth:
  enabled: true

  # To disable these filters set them to "null" or "none"
  pre: transpose # name of filter within ./vpys/$NAME$, applied BEFORE ffmpeg noise and upscaled
  pos: transpose # name of filter within ./vpys/$NAME$, applied after everything

developer:
  loglevel: 5
  wait_time_exists: 0.05
  waifu2x_wait_for_residuals: 1 # time waifu2x sleeps after upscaling everything or nothing from residuals

specific: # just ideas at the moment
  colors_output: true # doesn't work yet
  log_full_path: false # Log full path instead of relative path to D2X's ROOT folder

debug:
  enable_waifu2x: true



