session_name: "default"
waifu2x_type: "vulkan"

basic:
  input_file: "test720p.mp4"
  output_file: "asidjasio"

processing:
  block_size: "auto"
  bleed: 2

specific:
  colors_output: true # doesn't work yet
  log_full_path: false # Log full path instead of relative path to D2X's ROOT folder

developer:
  debug: true