# ===============================================================================
#
# Purpose: General settings for a Dandere2x session
#
# ===============================================================================
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# ===============================================================================

# The options are written as:
#
# [option]: [value]  # Info or possible values


session_name: auto
waifu2x_type: vulkan  # fake, cpp, vulkan
block_size: 20
mindisk: true

# These are how agressive the block matching is, lower values will catch more blocks;
# dark and bright are determined by the mean pixel value of every channel on a frame
# and then apply a linear function to get the final threshold, 0=dark, 255=bright
# This seems to make block matching better as darker frames not a lot of colors are moving
dark_threshold: 0.004
bright_threshold: 0.005


basic:
  input_file: samples/yn_moving_480.mkv
  output_file: auto  # "auto" adds a "2x_" prefix to the filename in the same directory

waifu2x:
  denoise_level: 3
  tile_size: 200
  linux_enable_mesa_aco_waifu2x_vulkan: false  # Only for AMD GPUs

  waifu2x_model: models-cunet  # Only Vulkan utilizes this now

danger_zone:
  force: false  # Forces resume=False

video:
  get_frame_count_method: null_copy  # Only option available right now
  get_frame_rate_method: ffprobe  # Only option available right now
  get_resolution_method: ffprobe  # Only option available right now
  get_video_info_method: ffmpeg  # FFmpeg or mediainfo

ffmpeg:
  deblock_filter: "pp=hb/vb/dr/fq|32, deband=range=22:blur=false"
  encode_codec: libx264

processing:
  extracted_images_extension: .jpg
  bleed: 1

vapoursynth:
  enabled: false
  # To disable these filters set them to "null" or "none"
  pre: transpose  # name of filter within ./vpys/$NAME$, applied BEFORE ffmpeg noise and upscaled
  pos: transpose  # name of filter within ./vpys/$NAME$, applied after everything

developer:
  loglevel: 4
  safety_ruthless_residual_eliminator_range: 3
  wait_time_exists: 0.05
  waifu2x_wait_for_residuals: 0.1  # time waifu2x sleeps after upscaling everything or nothing from residuals

specific:  # Just ideas at the moment
  colors_output: true  # Doesn't work yet

debug:
  write_only_debug_video: false
  enable_waifu2x: true
